(TeX-add-style-hook "qd"
 (lambda ()
    (LaTeX-add-bibliographies)
    (LaTeX-add-environments
     "thm"
     "defn"
     "lem"
     "prop"
     "alg")
    (LaTeX-add-labels
     "sec:intro"
     "sec:prelim"
     "quick_two_sum_fig"
     "two_sum_fig"
     "two_prod_fig"
     "normal_sum_prod_fig"
     "sec:basic"
     "renorm_alg"
     "qd_add_qd_d_fig"
     "qd_add_fig"
     "three_sum_fig"
     "two_sum_bound"
     "three_sum_bound"
     "sum_lemma"
     "double_accum_alg"
     "accurate_add_alg"
     "qd_mul_qd_d_fig"
     "qd_mul_accum_fig"
     "six_three_sum_fig"
     "nine_two_sum_fig"
     "sec:algebraic"
     "sec:transcendental"
     "sec:misc"
     "sec:implement"
     "sec:performance"
     "timing_table"
     "sec:future"
     "proof_appendix"
     "qd_add_proof_fig")
    (TeX-add-symbols
     "round"
     "fl"
     "err"
     "ulp"
     "hi"
     "lo"
     "eps"
     "epsqd")
    (TeX-run-style-hooks
     "amsthm"
     "graphicx"
     "latex2e"
     "art11"
     "article"
     "11pt")))

